global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: medibot-backend
    static_configs:
      - targets:
          - fastapi-backend:8000
    metrics_path: /metrics
